# Generated by Django 4.0.4 on 2022-05-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AC_Room', models.CharField(max_length=100)),
                ('Non_AC_Room', models.CharField(max_length=100)),
            ],
        ),
    ]
